// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// eslint-disable-next-line prettier/prettier
import "dotenv/config";
// eslint-disable-next-line prettier/prettier
import { defineConfig } from "prisma/config";

export default defineConfig({
  // eslint-disable-next-line prettier/prettier
  schema: "prisma/schema.prisma",
  migrations: {
    // eslint-disable-next-line prettier/prettier
    path: "prisma/migrations",
    // eslint-disable-next-line prettier/prettier
    seed: "ts-node ./prisma/seed.ts",
  },
  datasource: {
    // eslint-disable-next-line prettier/prettier
    url: process.env["DATABASE_URL"],
  },
});
